### ISSUE TITLE
Can't refresh the protocol after the latest release yesterday. 

### ISSUE THREAD

**Issue by macnibblet** [paralin/go-dota2#10]
I tried to edit the `update_protos.bash` sed for replacing `.` in the protobuf files but to no available.
So I managed to edit the files I needed in the protocol folder and regenerate the protobuf from there. 

Another thing I noticed which is that the newer files are generated with `ProtoPackageIsVersion4` instead of `ProtoPackageIsVersion3`

**Comment by paralin** [comment]
@macnibblet fixed it, I don't see any need to update script, use `make gengo` to refresh the protos.

Let me know if that doesn't work (it's updated to latest at the moment).

**Comment by macnibblet** [comment]
What versions of protoc and it's go plugin are you on? 
```
➜ generator git:(master) ./update_protos.bash
steammessages.proto:80:18: "CMsgHttpRequestRequestHeader" is not defined.
steammessages.proto:81:18: "CMsgHttpRequestQueryParam" is not defined.
steammessages.proto:82:18: "CMsgHttpRequestQueryParam" is not defined.
steammessages.proto:195:18: "CGCMsgMemCachedSetKeyPair" is not defined.
base_gcmessages.proto:4:1: Import "steammessages.proto" was not found or had errors.
```

**Comment by paralin** [comment]
@macnibblet Use `make gengo` to refresh the protos.

**Comment by macnibblet** [comment]
Same error with gengo
```
➜ go-dota2 git:(master) make gengo
export PATH=$(pwd)/hack/bin:${PATH}; \
	cd ./generator && ./update_protos.bash; \
	cd ../apigen && ./apigen.bash
steammessages.proto:80:18: "CMsgHttpRequestRequestHeader" is not defined.
steammessages.proto:81:18: "CMsgHttpRequestQueryParam" is not defined.
steammessages.proto:82:18: "CMsgHttpRequestQueryParam" is not defined.
steammessages.proto:195:18: "CGCMsgMemCachedSetKeyPair" is not defined.
base_gcmessages.proto:4:1: Import "steammessages.proto" was not found or had errors.
```

**Comment by paralin** [comment]
@macnibblet Check your hack/bin dir... Should be protoc-gen-go there.

Only thing that isn't controlled there is `protoc` version, mine is `libprotoc 3.11.4` - maybe that's why?

**Comment by macnibblet** [comment]
Hmm I have the files, but I do have a newer version of libprotoc

```
➜ bin git:(master) ✗ ll
total 88320
-rwxr-xr-x  1 antoine  staff    29M Sep  5 21:18 golangci-lint
-rwxr-xr-x  1 antoine  staff   8.0M Sep  5 21:17 protoc-gen-go
-rwxr-xr-x  1 antoine  staff   5.9M Sep  5 21:16 protowrap
➜ bin git:(master) ✗ protoc --version
libprotoc 3.13.0
```

**Comment by paralin** [comment]
I keep updating the protos every release so, all good, right? :)
