### ISSUE TITLE
can you update paralin/Dota2 

### ISSUE THREAD

**Issue by jellyr** [paralin/go-dota2#11]
I'm still using your https://github.com/paralin/Dota2 to create lobby. but lots of proto are outdate. I donot know how to generate all these .cs file using proto.
I'm using dota_gcmessages_common_match_management.proto this protocol to automatically create lobby and get lobby status.but it doesn't work anymore. I know this go-dota2 project using latest proto, but I'm not familiar with go, sorry.
Would you please update the proto, or tell me how to generate all that cs files according proto file. Thanks very much!

**Comment by paralin** [comment]
I dont' use C# anymore if someone wants to update via a PR it I can merge.

**Comment by jellyr** [comment]
ok, I see.
