### ISSUE TITLE
Would it be possible to retrieve live in game chat?

### ISSUE THREAD

**Issue by felixmr1** [paralin/go-dota2#17]
I do not really understand the inner workings of this SDK, but looking at the protos: https://github.com/paralin/go-dota2/blob/master/protos/valve_extensions.proto

lead me here: https://github.com/SteamDatabase/Protobufs/blob/dbe824b12ec4efd3b8f9fa8b7a2b07f8af25146a/dota2/dota_gcmessages_common_bot_script.proto#L385

So what do you think, would it be possible?

**Comment by paralin** [comment]
Not currently, afaik.
