### ISSUE TITLE
Can I create a lobby with 10 custom players using this package?

### ISSUE THREAD

**Issue by j0m0k0** [paralin/go-dota2#18]
Hi, 
Can I create a lobby with 10 custom players using this package? and control that lobby? like starting the game or deleting the lobby?

**Comment by paralin** [comment]
Yes, but you'll have to manage the process of creating the lobby, inviting, waiting for players, starting, etc.

**Comment by di-sukharev** [comment]
how do i create a lobby and invite players programatically?

**Comment by paralin** [comment]
Yes
