### ISSUE TITLE
the dota2 is not ready

### ISSUE THREAD

**Issue by jacobxy** [paralin/go-dota2#2]
the dota client is not ready to accept requests yet, or has just become unready.

dota2Client := dota.New(client, logrus.NewEntry(logrus.New()))
dota2Client.RequestMatchDetails(ctx, matchID) 
How can I find the ctx?

**Comment by paralin** [comment]
```go
	switch e := event.(type) {
	case *events.GCConnectionStatusChanged:
		isReady := e.NewState == gcsdk_gcmessages.GCConnectionStatus_GCConnectionStatus_HAVE_SESSION
		b.setReady(isReady)
		if !isReady {
		    b.dotaClient.SayHello()
		}
	}
```

You have to set your games played to dota (570), SayHello to the Dota GC, wait for it to issue you a session.

Context is given by `context.Background()` and `import "context"`

I should add some examples to this repo, but it's not exactly designed to be easy to get started with yet, it's more of an internal tool at this point.
