### ISSUE TITLE
Concurrency problems

### ISSUE THREAD

**Issue by zethuman** [paralin/go-dota2#20]
Hi there,

I ran into a problem that I can not call functions in the goroutine. I get the *same* result every time.

Whether prompt means it that functions cannot be asynchronous? 
Or does it store the cache somewhere? If so, how can I reset it in order to get normal responses in goroutines?

Bellow is my implementation and results

`Concurrently in goroutines without time delay`

![telegram-cloud-photo-size-2-5442943494114098942-y](https://user-images.githubusercontent.com/51375666/201506188-ffc7d6a0-4693-470d-8697-2ce7278efcd6.jpg)

`Consistently in goroutines with time delay`

![telegram-cloud-photo-size-2-5442943494114098943-y](https://user-images.githubusercontent.com/51375666/201506190-8cf1dc4a-9acd-4ea0-9056-c60c05885c23.jpg)

Thanks in advance!

**Comment by paralin** [comment]
This is a limitation of the Dota2 game coordinator.

https://github.com/paralin/go-dota2/blob/master/client.go#L162

Note that we match the response message to the request based on the message type.

Therefore we cannot distinguish between two response messages of the same type, as to which request they came from.

Please just send your requests in serial (don't send multiple concurrent requests with the same message type).
