### ISSUE TITLE
WARN: Unable to handle welcome cache

### ISSUE THREAD

**Issue by k0mar12** [paralin/go-dota2#23]
Hello.

While trying to run dota like this:

```
func runDota(c *steam.Client) {
  log := &log.Logger{
  Out:       os.Stderr,
  Formatter: new(log.TextFormatter),
  Hooks:     make(log.LevelHooks),
  Level:     log.DebugLevel,
  }
  
  game := dota2.New(c, log)
  
  game.SayHello()
  game.SetPlaying(true)
}
```

Got this warn:

```
DEBU[0001] sending hello to GC                          
DEBU[0001] received GC welcome                          
WARN[0001] unable to handle welcome cache                error="unknown shared object type id: 2012"
DEBU[0001] connection status changed                     new=GCConnectionStatus_HAVE_SESSION old=GCConnectionStatus_NO_SESSION
DEBU[0001] unhandled cache issue (ignore)                error="unknown shared object type id: 7"
```

Same issue exist in node-dota2.

**Comment by k0mar12** [comment]
In node-dota2 i got next error:

`Illegal wire type for field Message.Field .CMsgSOCacheSubscribed.service_list: 2 (0 expected)`

So, perhaps, problem in protobuf.

**Comment by k0mar12** [comment]
I have spent one day to get basics of go and one more to dig into this module to get same error as in node-dota 2 😂
Life is good :)

**Comment by k0mar12** [comment]
And this warn i getting time to time.
Usually, i don't even get event **Client Welcomed**

**Comment by paralin** [comment]
You have to call SetPlaying(true), wait a moment, then send SendHello until you get a session and/or a "in session queue" message.

Ignore the unable to handle welcome cache messages... They are just warnings.
