### ISSUE TITLE
Is it possibly to create lobby, take a spectator slot, launch it and get result of a match?

### ISSUE THREAD

**Issue by kendis-fit** [paralin/go-dota2#28]
if it is really possibly, then I have issues with creating lobby. I feel maybe the lobby doesn't have enough of arguments or it is supposed to use in another event.

```
case *steam.LoggedOnEvent:
	log.Printf("Logged")
	client.Social.SetPersonaState(steamlang.EPersonaState_Online)

	dota2Client := dota2.New(client, logrus.NewEntry(logrus.New()))

	dota2Client.SetPlaying(true)
	
	dota2Client.CreateLobby(&gcccm.CMsgPracticeLobbySetDetails{
		AllowCheats: proto.Bool(false),
		GameName: proto.String("test123qwe"),
		FillWithBots: proto.Bool(false),
		PassKey: proto.String("qwe123test"),
	})
	
	log.Printf("Success")

```

**Comment by kendis-fit** [comment]
I have seen method which creates and launches lobbies, but I couldn't find the rest needed methods

**Comment by paralin** [comment]
You have to wait for the client to have a GC session before calling create lobby.

 1. SetPlaying(true)
 2. Wait a moment (like 0.5 second)
 3. SayHello()
 4. Wait for the connection status event to indicate you have a gc session (IsReady() = true)
 5. Send SayHello every few seconds until you get a session
 6. Once you have IsReady() = true send CreateLobby.

It's not as easy as just calling a few function simultaneously. unfortunately.
