### ISSUE TITLE
Where to find some example code?

### ISSUE THREAD

**Issue by nyxnyxnyxdota** [paralin/go-dota2#29]
I'm completely new to this project.
I want to write a simple app that given a Dota 2 match ID, retrieves the match info from the GC.

Can you point me to docs/examples on how to ahieve this please?

Thank you!

**Comment by paralin** [comment]
The code is a bit vague on purpose so that this repo is not used to make a flood of low-quality bots.

Please just read the api docs and you'll see how to use it.

**Comment by nyxnyxnyxdota** [comment]
I see. I respect the reasoning, thank you.
