### ISSUE TITLE
How to pass `AuthCode string` (Guard Code) programatically?

### ISSUE THREAD

**Issue by di-sukharev** [paralin/go-dota2#37]
how do i pass LogOnDetails.AuthCode programatically it's being send to my email?

do i parse an email and restart the bot with the AuthCode set to the Code i get from steam email?

How should I manage this? What happens if i dont pass the AuthCode?

**Comment by paralin** [comment]
When you attempt to sign in with an empty auth code it will return a log in failed event saying the auth code was sent to email. Then you can try to log in again with the code set.
