### ISSUE TITLE
[Request] Remove logger from options

### ISSUE THREAD

**Issue by Satont** [paralin/go-dota2#42]
I'm feeling require logger is not good idea for 3rd party lib not related to logger itself.

For me it produces unwanted logs in console, also i need to use `logrus` in my project even if i already used own one with some hooks, maybe sentry, e.t.c, it also push me to download another dependency in project which is also unwanted.

I can do PR if you agree with this change and you haven't time to do this yourself.

**Comment by paralin** [comment]
You can disable the logs by using a NoopLogger. The logs are critical for understanding what is going on internally in the library. Sorry but not changing this. Thanks.
