### ISSUE TITLE
panic: proto: file "base_gcmessages.proto" is already registered (And some other proto files)

### ISSUE THREAD

**Issue by Masedko** [paralin/go-dota2#47]
Hi, I use go-dota2 and go-steam.
But during the build I get 
`panic: proto: file "base_gcmessages.proto" is already registered`
I found some workaround by using 
`go build -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn"`
But that's not a good solution, am I missing something?

**Comment by paralin** [comment]
@Masedko Thanks for the report, I'll look into this if/when I get time. If you find a solution in the meantime please let me know here

**Comment by paralin** [comment]
As far as i know this is working now?
