### ISSUE TITLE
 create a lobby

### ISSUE THREAD

**Issue by xDes-by** [paralin/go-dota2#51]
I have 2 problems
1) I create a lobby with details for a custom game, it is created, but my lobby is not valid, i.e. I don’t see it in the general list of all lobbies, and this is the most important point
2) I was never able to enter the created lobby as a bot, it always writes to me that the bot is not ready, I still can’t understand what this is connected with.

**Comment by paralin** [comment]
1. You have to set the lobby to public I think.
2. Not sure what you mean but you can't start the lobby with just bots. All the players have to connect.

**Comment by paralin** [comment]
Hi, I don't have time available to help w/ go-dota2 at the moment, my apologies. You'll have to figure this one out.

**Comment by yuanhongguo** [comment]
Have you already solved this problem? I have the same problem, can you share your solution
