### ISSUE TITLE
Can this tool monitor user matches in practice mode?

### ISSUE THREAD

**Issue by Zakhar02** [paralin/go-dota2#60]
Currently I am searching for the way to monitor practice matches e. g. 1v1 Solo mid using game coordintor. Can I use this app for such purpose?

Thanks in advance

**Comment by Zakhar02** [comment]
Just have tested with GSI, works fine, but it would be nice if there is a more user friendly way to collect match statistics

**Comment by paralin** [comment]
Glad to hear you found a way. PRs always accepted.
