### ISSUE TITLE
Accept party request!

### ISSUE THREAD

**Issue by iamalirezaj** [paralin/go-dota2#7]
I want to accept a party request after i receive one
I managed to get the party invite from `cso.PartyInvite` channel like so:
```go
partyInviteCh, _, err := dota2Client.GetCache().SubscribeType(cso.PartyInvite)
if err != nil {
    log.Println(err)
}
```

Now i want to accept the party request, i searched a little bit on the package to see if there's any AcceptParty like method but i found a method called `JoinPartyFromBeacon`

can anyone explain to me, am i going in right direction?
Should i call `JoinPartyFromBeacon` method to accept the invitation ?

if yes, what are the `(partyID uint64), (accountID uint32), (beaconType int32)` arguments?

Thanks

**Comment by paralin** [comment]
Merged the PR, is this solved?

**Comment by iamalirezaj** [comment]
Yes, thanks for the merge!
